-- 코드를 작성해주세요


# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE BIN(SKILL_CODE) LIKE "%1____"
#     OR BIN(SKILL_CODE) LIKE '%1___________'
#     OR BIN(SKILL_CODE) LIKE '%1_____________'
# ORDER BY ID ASC

# SELECT * 
# FROM DEVELOPERS d, SKILLCODES s


SELECT ID
        ,EMAIL
        ,FIRST_NAME
        ,LAST_NAME
FROM DEVELOPERS D, SKILLCODES S
WHERE (D.SKILL_CODE & S.CODE) > 0
    AND CATEGORY = 'Front End'
GROUP BY ID, EMAIL, FIRST_NAME, LAST_NAME
ORDER BY ID;