-- 코드를 입력하세요
# SELECT *
# FROM USED_GOODS_BOARD a
# LEFT JOIN USED_GOODS_FILE b ON a.BOARD_ID = b.BOARD_ID
# ORDER BY VIEWS DESC



SELECT CONCAT('/home/grep/src/', BOARD_ID, '/' ,FILE_ID, FILE_NAME, FILE_EXT)  
FROM USED_GOODS_FILE
WHERE BOARD_ID =
    (
    SELECT BOARD_ID             # 조회수 가장 높은 BOARD_ID 추출 
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
    )
ORDER BY FILE_ID DESC